---
- name: Create nexus dirs
  file:
    path: "{{item}}"
    state: directory
    mode: '0777'
    recurse: yes
    owner: "{{ansible_ssh_user}}"
    group: "{{ansible_ssh_group}}"
  with_items:
    - "{{directory_deploy_nexus}}"
    - "{{directory_deploy_volumes}}/nexus/nexus-data/etc"
  become: true

- name: Upload updateNexus.sh
  template:
    src: "templates/updateNexus.sh.j2"
    dest: "{{directory_deploy_nexus}}/updateNexus.sh"
    owner: "{{ansible_ssh_user}}"
    group: "{{ansible_ssh_group}}"
    mode: '0755'

- name: Upload docker-compose nexus
  template:
    src: "templates/docker-compose.yml.j2"
    dest: "{{directory_deploy_nexus}}/docker-compose.yml"
    owner: "{{ansible_ssh_user}}"
    group: "{{ansible_ssh_group}}"
    mode: '0644'

- name: Copy nexus.properties
  copy:
    src: files/nexus.properties
    dest: "{{directory_deploy_volumes}}/nexus/nexus-data/etc/"
    owner: "{{ansible_ssh_user}}"
    group: "{{ansible_ssh_group}}"
    mode: '0644'

- name: Execute docker-compose
  command: chdir="{{directory_deploy_nexus}}/" docker-compose up -d
  become: true

- name: Upload nexus.conf
  template:
    src: "templates/nexus.conf.j2"
    dest: "{{directory_deploy_volumes}}/nginx/conf.d/nexus.conf"
    owner: "{{ansible_ssh_user}}"
    group: "{{ansible_ssh_group}}"
    mode: '0644'

- name: Restart nginx
  command: "docker restart nginx"
  become: true

- name: Pause play until a URL is reachable from this host
  uri:
    url: "http://{{nexus_domain}}"
    follow_redirects: none
    method: GET
  register: _result
  until: _result.status == 200
  retries: 30 # 30 * 5 seconds = 150secs
  delay: 5 # Every 5 seconds

- name: Delete existing nexus script with PUT
  uri: 
    url: http://{{nexus_domain}}/service/rest/v1/script/docker
    method: DELETE
    user: "admin"
    password: "admin123"
    force_basic_auth: yes
    return_content: yes
    status_code:
      - 204
      - 404

- name: Add nexus script
  uri: 
    url: http://{{nexus_domain}}/service/rest/v1/script
    method: POST
    user: "admin"
    password: "admin123"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{{ lookup('file','files/docker.json') }}"
    status_code: 204

- name: Run nexus script for create docker registry repo
  uri: 
    url: http://{{nexus_domain}}/service/rest/v1/script/docker/run
    method: POST
    user: "admin"
    password: "admin123"
    force_basic_auth: yes
    return_content: yes
    headers:
      Content-Type: text/plain
    status_code: 200
